#!/usr/bin/env python3
"""
Generate Inno Setup installer script programmatically.

This script creates the installer.iss file with the correct version number
extracted from VERSION file or command-line argument.

Usage:
    python generate_installer.py [version]

If no version is provided, reads from ../VERSION file.
"""

import sys
import os
from pathlib import Path


def get_version():
    """Get version from command line or VERSION file."""
    if len(sys.argv) > 1:
        version = sys.argv[1].strip()
        print(f"Using version from command line: {version}")
        return version

    # Try to read from VERSION file (in parent directory)
    version_file = Path(__file__).parent.parent / 'VERSION'
    print(f"Looking for VERSION file at: {version_file}")
    if version_file.exists():
        version = version_file.read_text(encoding='utf-8').strip()
        print(f"Using version from VERSION file: {version}")
        return version

    # Default version
    version = "0.0.0"
    print(f"No version found, using default: {version}")
    return version


def extract_numeric_version(version):
    """Extract numeric part from version string (removes -alpha, -beta, etc)."""
    if '-' in version:
        return version.split('-')[0]
    return version


def generate_iss_content(version):
    """Generate the Inno Setup script content."""
    numeric_version = extract_numeric_version(version)

    return f'''; JobDocs Inno Setup Installer Script
; Auto-generated by generate_installer.py - DO NOT EDIT MANUALLY
; Creates a Windows installer for JobDocs
; Requires Inno Setup: https://jrsoftware.org/isinfo.php

[Setup]
; Application information
AppName=JobDocs
AppVersion={version}
AppPublisher=JobDocs Developers
AppPublisherURL=https://github.com/i-machine-things/JobDocs
AppSupportURL=https://github.com/i-machine-things/JobDocs/issues
AppUpdatesURL=https://github.com/i-machine-things/JobDocs/releases
DefaultDirName={{autopf}}\\JobDocs
DefaultGroupName=JobDocs
AllowNoIcons=yes
LicenseFile=..\\LICENSE
OutputDir=..\\
OutputBaseFilename=JobDocs-Setup-{version}
SetupIconFile=icon.ico
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Version information (must be numeric X.X.X.X format)
VersionInfoVersion={numeric_version}.0
VersionInfoCompany=JobDocs Developers
VersionInfoDescription=JobDocs Installer
VersionInfoCopyright=Copyright (C) 2024 JobDocs Developers
VersionInfoProductName=JobDocs
VersionInfoProductVersion={numeric_version}.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: checkedonce

[Files]
Source: "..\\dist_temp\\jobdocs.exe"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "..\\LICENSE"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "..\\README.md"; DestDir: "{{app}}"; Flags: ignoreversion isreadme
Source: "icon.ico"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\JobDocs"; Filename: "{{app}}\\jobdocs.exe"; IconFilename: "{{app}}\\icon.ico"
Name: "{{group}}\\{{cm:UninstallProgram,JobDocs}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\JobDocs"; Filename: "{{app}}\\jobdocs.exe"; IconFilename: "{{app}}\\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\jobdocs.exe"; Description: "Launch JobDocs now"; Flags: nowait postinstall skipifsilent

[Messages]
WelcomeLabel2=This will install JobDocs on your computer.%n%nJobDocs helps you manage blueprint files and customer job folders.%n%nClick Next to continue.
FinishedLabel=JobDocs has been installed successfully!%n%nYou can now find JobDocs in the Start Menu and on your Desktop (if selected).%n%nClick Finish to complete the installation.

[Registry]
Root: HKCU; Subkey: "Software\\JobDocs"; ValueType: string; ValueName: "InstallPath"; ValueData: "{{app}}"; Flags: uninsdeletekey
'''


def main():
    """Main function to generate the installer script."""
    version = get_version()

    # Generate ISS content
    iss_content = generate_iss_content(version)

    # Write to installer.iss
    output_file = Path(__file__).parent / 'installer.iss'
    output_file.write_text(iss_content, encoding='utf-8')

    print(f"[OK] Generated {output_file}")
    print(f"  Version: {version}")
    print(f"  Numeric version: {extract_numeric_version(version)}.0")

    return 0


if __name__ == '__main__':
    sys.exit(main())
