#!/usr/bin/env python3
"""
Generate Inno Setup installer script.

Usage:
    python generate_installer.py
"""

import sys
from pathlib import Path


def generate_iss_content():
    """Generate the Inno Setup script content."""
    return '''; JobDocs Inno Setup Installer Script
; Auto-generated by generate_installer.py - DO NOT EDIT MANUALLY
; Creates a Windows installer for JobDocs
; Requires Inno Setup: https://jrsoftware.org/isinfo.php

[Setup]
; Application information
AppName=JobDocs
AppVersion=0.0.0
AppPublisher=JobDocs Developers
AppPublisherURL=https://github.com/i-machine-things/JobDocs
AppSupportURL=https://github.com/i-machine-things/JobDocs/issues
AppUpdatesURL=https://github.com/i-machine-things/JobDocs/releases
DefaultDirName={autopf}\\JobDocs
DefaultGroupName=JobDocs
AllowNoIcons=yes
LicenseFile=..\\LICENSE
OutputDir=..\\
OutputBaseFilename=JobDocs-Setup
SetupIconFile=icon.ico
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Version information (must be numeric X.X.X.X format)
VersionInfoCompany=JobDocs Developers
VersionInfoDescription=JobDocs Installer
VersionInfoCopyright=Copyright (C) 2026 JobDocs Developers
VersionInfoProductName=JobDocs
VersionInfoVersion=0.0.0.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
Source: "..\\dist_temp\\jobdocs.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\\README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\\JobDocs"; Filename: "{app}\\jobdocs.exe"; IconFilename: "{app}\\icon.ico"
Name: "{group}\\{cm:UninstallProgram,JobDocs}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\\JobDocs"; Filename: "{app}\\jobdocs.exe"; IconFilename: "{app}\\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\\jobdocs.exe"; Description: "Launch JobDocs now"; Flags: nowait postinstall skipifsilent

[Messages]
WelcomeLabel2=This will install JobDocs on your computer.%n%nJobDocs helps you manage blueprint files and customer job folders.%n%nClick Next to continue.
FinishedLabel=JobDocs has been installed successfully!%n%nYou can now find JobDocs in the Start Menu and on your Desktop (if selected).%n%nClick Finish to complete the installation.

[Registry]
Root: HKLM; Subkey: "Software\\JobDocs"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Flags: uninsdeletekey
'''


def main():
    output_file = Path(__file__).parent / 'installer.iss'
    try:
        output_file.write_text(generate_iss_content(), encoding='utf-8')
    except OSError as e:
        print(f"[ERROR] Failed to write {output_file}: {e}", file=sys.stderr)
        return 1
    print(f"[OK] Generated {output_file}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
