# Auto-generated by the CI release workflow — do not edit manually.
# In development this file contains "dev"; the build pipeline overwrites
# it with the actual release tag (e.g. "v1.2.3") before packaging.
__version__ = "dev"
